### ISSUE TITLE
Ограничить список файлов, изменения которых коммитятся при релизе

### ISSUE THREAD

**Issue by layfe** [yoomoney-gradle-plugins/artifact-release-plugin#10]
сейчас при выпуске релиза плагин коммитит все изменения.
это может быть нежелательно, например, в случаях, когда при сборке проекта появляются побочные файлы, коммит которых в проект не нужен.

надо ввести новую настройку в Extension, в которую можно добавить список файлов и производить коммит только для этого списка.

**Comment by DivXor** [comment]
@layfe точно стоит управлять исключениями на уровне конфигурации плагина, а не на уровне .gitignors ?

**Comment by f0y** [comment]
Может и там и там лучше? Вообще непонятно зачем релизному плагину коммитить что-то кроме версии и changelog. Это явно не типичный случай.

**Comment by layfe** [comment]
соответствие внутреннему багтрекеру: BACKEND-4767
